### ISSUE TITLE
Update the package creation workflow to generate release notes

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-scripts-pipeline#3]

**Comment by levisingularity** [comment]
Investigating the code I managed to discover the problem. The previously created tags were created directly on github which does not maintain the reference in .git, to create the release I need this reference to use the command `git log --oneline --abbrev-commit --no-merges $(git describe --tags --abbrev=0)..HEAD`. Now that a commit with the necessary reference has been generated, the next time it is run again, the script should work normally as expected.

**Comment by levisingularity** [comment]
I made a small change in the way the commit messages are gathered

@andre-senna When you have some time to approve my pr: https://github.com/singnet/das-scripts-pipeline/pull/4
